[2024-08-13 21:53:22] [INFO    ] discord.client: logging in using static token
[2024-08-13 21:53:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6dd502f8be5850431cb0207b2d6cc0cb).
[2024-08-13 21:54:57] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 184, in <module>
    bot.run(os.getenv("DISCORD_TOKEN"), log_handler=handler)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 33, in on_message
    await bot.process_commands(message)  # Ensure commands are processed
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 113, in generate
    response = requests.post(api_url, headers=headers, json=data)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1411, in getresponse
    response.begin()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 324, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)

[2024-08-13 21:55:07] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 184, in <module>
    bot.run(os.getenv("DISCORD_TOKEN"), log_handler=handler)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 33, in on_message
    await bot.process_commands(message)  # Ensure commands are processed
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 113, in generate
    response = requests.post(api_url, headers=headers, json=data)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1411, in getresponse
    response.begin()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 324, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)

[2024-08-13 21:55:13] [ERROR   ] discord.client: Attempting a reconnect in 1.77s
Traceback (most recent call last):
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 667, in connect
    await self.ws.poll_event()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 648, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-08-13 21:55:16] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 6dd502f8be5850431cb0207b2d6cc0cb.
[2024-08-13 21:56:48] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 184, in <module>
    bot.run(os.getenv("DISCORD_TOKEN"), log_handler=handler)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 33, in on_message
    await bot.process_commands(message)  # Ensure commands are processed
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 113, in generate
    response = requests.post(api_url, headers=headers, json=data)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1411, in getresponse
    response.begin()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 324, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)

[2024-08-13 21:56:57] [ERROR   ] discord.client: Attempting a reconnect in 2.71s
Traceback (most recent call last):
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 667, in connect
    await self.ws.poll_event()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 648, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-08-13 21:57:01] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 6dd502f8be5850431cb0207b2d6cc0cb.
[2024-08-13 22:19:11] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 184, in <module>
    bot.run(os.getenv("DISCORD_TOKEN"), log_handler=handler)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 33, in on_message
    await bot.process_commands(message)  # Ensure commands are processed
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 113, in generate
    response = requests.post(api_url, headers=headers, json=data)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1411, in getresponse
    response.begin()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 324, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)

[2024-08-13 22:19:21] [WARNING ] discord.gateway: Shard ID None heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 184, in <module>
    bot.run(os.getenv("DISCORD_TOKEN"), log_handler=handler)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 869, in run
    asyncio.run(runner())
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 651, in run_until_complete
    self.run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 618, in run_forever
    self._run_once()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1951, in _run_once
    handle._run()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 449, in _run_event
    await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 33, in on_message
    await bot.process_commands(message)  # Ensure commands are processed
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1408, in process_commands
    await self.invoke(ctx)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
  File "e:\Programming\Ei-Gen-Bot\src\index.py", line 113, in generate
    response = requests.post(api_url, headers=headers, json=data)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connection.py", line 464, in getresponse
    httplib_response = super().getresponse()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1411, in getresponse
    response.begin()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 324, in begin
    version, status, reason = self._read_status()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1249, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1105, in read
    return self._sslobj.read(len, buffer)

[2024-08-13 22:19:21] [ERROR   ] discord.client: Attempting a reconnect in 2.51s
Traceback (most recent call last):
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\client.py", line 667, in connect
    await self.ws.poll_event()
  File "C:\Users\rishi\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\gateway.py", line 648, in poll_event
    raise ConnectionClosed(self.socket, shard_id=self.shard_id, code=code) from None
discord.errors.ConnectionClosed: Shard ID None WebSocket closed with 1000
[2024-08-13 22:19:25] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 6dd502f8be5850431cb0207b2d6cc0cb.
